spring.application.name=service-center-backend
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:examSecretKeyForJwtTokenGenerationExamSecretKeyForJwtTokenGeneration2026}
jwt.expiration=${JWT_EXPIRATION:86400000}

springdoc.swagger-ui.path=/swagger-ui.html
